// DO NOT MODIFY THIS FILE
// This file was autogenerated.

package main

import "testing"

func init() {
	// TODO: setup default test runner if necessary.
}

func TestQuadStoreCreate(t *testing.T) { (Runner).Run(t, "TestQuadStoreCreate", TestQuadStoreCreate) }

func TestQuadStoreLoadFixture(t *testing.T) {
	(Runner).Run(t, "TestQuadStoreLoadFixture", TestQuadStoreLoadFixture)
}

func TestQuadStoreRemoveQuad(t *testing.T) {
	(Runner).Run(t, "TestQuadStoreRemoveQuad", TestQuadStoreRemoveQuad)
}

func TestQuadStoreNodesAllIterator(t *testing.T) {
	(Runner).Run(t, "TestQuadStoreNodesAllIterator", TestQuadStoreNodesAllIterator)
}

func TestQuadStoreQuadsAllIterator(t *testing.T) {
	(Runner).Run(t, "TestQuadStoreQuadsAllIterator", TestQuadStoreQuadsAllIterator)
}

func TestQuadStoreQuadIterator(t *testing.T) {
	(Runner).Run(t, "TestQuadStoreQuadIterator", TestQuadStoreQuadIterator)
}

func TestQuadStoreQuadIteratorAnd(t *testing.T) {
	(Runner).Run(t, "TestQuadStoreQuadIteratorAnd", TestQuadStoreQuadIteratorAnd)
}

func TestQuadStoreQuadIteratorReset(t *testing.T) {
	(Runner).Run(t, "TestQuadStoreQuadIteratorReset", TestQuadStoreQuadIteratorReset)
}
