// DO NOT MODIFY THIS FILE
// This file waus autogenerated by ./gentest.sh.

package main

// AllTests is a list of all tests defined in the qstests package.
var AllTests = []*Test{
	{"github.com/bmatsuo/cayley/graph/graphtest/qstest", "TestQuadStoreCreate"},
	{"github.com/bmatsuo/cayley/graph/graphtest/qstest", "TestQuadStoreLoadFixture"},
	{"github.com/bmatsuo/cayley/graph/graphtest/qstest", "TestQuadStoreRemoveQuad"},
	{"github.com/bmatsuo/cayley/graph/graphtest/qstest", "TestQuadStoreNodesAllIterator"},
	{"github.com/bmatsuo/cayley/graph/graphtest/qstest", "TestQuadStoreQuadsAllIterator"},
	{"github.com/bmatsuo/cayley/graph/graphtest/qstest", "TestQuadStoreQuadIterator"},
	{"github.com/bmatsuo/cayley/graph/graphtest/qstest", "TestQuadStoreQuadIteratorAnd"},
	{"github.com/bmatsuo/cayley/graph/graphtest/qstest", "TestQuadStoreQuadIteratorReset"},
}
