#!/bin/bash

set -e

QSTEST_IMPORT_PATH="github.com/bmatsuo/cayley/graph/graphtest/qstest"
QSTEST_PATH="../../qstest"
TESTS="$(grep '^func Test' "$QSTEST_PATH/tests.go" | sed 's/^func //' | sed 's/(.*$//')"

echo -n > alltests.go

cat << EOF >> alltests.go
// DO NOT MODIFY THIS FILE
// This file waus autogenerated by $0.

package main

// AllTests is a list of all tests defined in the qstests package.
var AllTests = []*Test{
EOF
for testfn in ${TESTS[@]}; do
	echo "	{\"$QSTEST_IMPORT_PATH\", \"$testfn\"}," >> alltests.go
done
cat << EOF >> alltests.go
}
EOF
